version: '2'

services:
  base-consul:
    build:
      context: .
    ports:
      - "1234:1234"
    volumes:
      - /etc/localtime:/etc/localtime:ro
    environment:
      - CONSULTEMPLATE_VERSION=${CONSULTEMPLATE_VERSION}
      - CONSUL_OPTIONS=${CONSUL_OPTIONS}                            # minimal server options
      - CONSUL_AGENT=172.16.0.1                                     # agent hostname
      - CONSUL_PORT=8500                                            # agent port
      - CONSUL_TLS=0                                                # enable TLS
      - CONSUL_SERVICENAME=base-consul                              # service name to register
      - CONSUL_SERVICEPORT=1234                                     # service port